<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TimezoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing timezones
        DB::table('timezones')->truncate();

        $timezones = [
            [1, 'AF', 'Afghanistan', 'Asia/Kabul', 'UTC +04:30', 'https://timezonedb.com/time-zones/Asia/Kabul'],
            [2, 'AL', 'Albania', 'Europe/Tirane', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Tirane'],
            [3, 'DZ', 'Algeria', 'Africa/Algiers', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Algiers'],
            [4, 'AS', 'American Samoa', 'Pacific/Pago_Pago', 'UTC -11:00', 'https://timezonedb.com/time-zones/Pacific/Pago_Pago'],
            [5, 'AD', 'Andorra', 'Europe/Andorra', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Andorra'],
            [6, 'AO', 'Angola', 'Africa/Luanda', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Luanda'],
            [7, 'AI', 'Anguilla', 'America/Anguilla', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Anguilla'],
            [8, 'AQ', 'Antarctica', 'Antarctica/Casey', 'UTC +11:00', 'https://timezonedb.com/time-zones/Antarctica/Casey'],
            [9, 'AQ', 'Antarctica', 'Antarctica/Davis', 'UTC +07:00', 'https://timezonedb.com/time-zones/Antarctica/Davis'],
            [10, 'AQ', 'Antarctica', 'Antarctica/DumontDUrville', 'UTC +10:00', 'https://timezonedb.com/time-zones/Antarctica/DumontDUrville'],
            [11, 'AQ', 'Antarctica', 'Antarctica/Mawson', 'UTC +05:00', 'https://timezonedb.com/time-zones/Antarctica/Mawson'],
            [12, 'AQ', 'Antarctica', 'Antarctica/McMurdo', 'UTC +13:00', 'https://timezonedb.com/time-zones/Antarctica/McMurdo'],
            [13, 'AQ', 'Antarctica', 'Antarctica/Palmer', 'UTC -03:00', 'https://timezonedb.com/time-zones/Antarctica/Palmer'],
            [14, 'AQ', 'Antarctica', 'Antarctica/Rothera', 'UTC -03:00', 'https://timezonedb.com/time-zones/Antarctica/Rothera'],
            [15, 'AQ', 'Antarctica', 'Antarctica/Syowa', 'UTC +03:00', 'https://timezonedb.com/time-zones/Antarctica/Syowa'],
            [16, 'AQ', 'Antarctica', 'Antarctica/Troll', 'UTC +02:00', 'https://timezonedb.com/time-zones/Antarctica/Troll'],
            [17, 'AQ', 'Antarctica', 'Antarctica/Vostok', 'UTC +06:00', 'https://timezonedb.com/time-zones/Antarctica/Vostok'],
            [18, 'AG', 'Antigua and Barbuda', 'America/Antigua', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Antigua'],
            [19, 'AR', 'Argentina', 'America/Argentina/Buenos_Aires', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/Buenos_Aires'],
            [20, 'AR', 'Argentina', 'America/Argentina/Catamarca', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/Catamarca'],
            [21, 'AR', 'Argentina', 'America/Argentina/Cordoba', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/Cordoba'],
            [22, 'AR', 'Argentina', 'America/Argentina/Jujuy', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/Jujuy'],
            [23, 'AR', 'Argentina', 'America/Argentina/La_Rioja', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/La_Rioja'],
            [24, 'AR', 'Argentina', 'America/Argentina/Mendoza', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/Mendoza'],
            [25, 'AR', 'Argentina', 'America/Argentina/Rio_Gallegos', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/Rio_Gallegos'],
            [26, 'AR', 'Argentina', 'America/Argentina/Salta', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/Salta'],
            [27, 'AR', 'Argentina', 'America/Argentina/San_Juan', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/San_Juan'],
            [28, 'AR', 'Argentina', 'America/Argentina/San_Luis', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/San_Luis'],
            [29, 'AR', 'Argentina', 'America/Argentina/Tucuman', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/Tucuman'],
            [30, 'AR', 'Argentina', 'America/Argentina/Ushuaia', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Argentina/Ushuaia'],
            [31, 'AM', 'Armenia', 'Asia/Yerevan', 'UTC +04:00', 'https://timezonedb.com/time-zones/Asia/Yerevan'],
            [32, 'AW', 'Aruba', 'America/Aruba', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Aruba'],
            [33, 'AU', 'Australia', 'Antarctica/Macquarie', 'UTC +10:00', 'https://timezonedb.com/time-zones/Antarctica/Macquarie'],
            [34, 'AU', 'Australia', 'Australia/Adelaide', 'UTC +09:30', 'https://timezonedb.com/time-zones/Australia/Adelaide'],
            [35, 'AU', 'Australia', 'Australia/Brisbane', 'UTC +10:00', 'https://timezonedb.com/time-zones/Australia/Brisbane'],
            [36, 'AU', 'Australia', 'Australia/Broken_Hill', 'UTC +09:30', 'https://timezonedb.com/time-zones/Australia/Broken_Hill'],
            [37, 'AU', 'Australia', 'Australia/Darwin', 'UTC +09:30', 'https://timezonedb.com/time-zones/Australia/Darwin'],
            [38, 'AU', 'Australia', 'Australia/Eucla', 'UTC +08:45', 'https://timezonedb.com/time-zones/Australia/Eucla'],
            [39, 'AU', 'Australia', 'Australia/Hobart', 'UTC +10:00', 'https://timezonedb.com/time-zones/Australia/Hobart'],
            [40, 'AU', 'Australia', 'Australia/Lindeman', 'UTC +10:00', 'https://timezonedb.com/time-zones/Australia/Lindeman'],
            [41, 'AU', 'Australia', 'Australia/Lord_Howe', 'UTC +10:30', 'https://timezonedb.com/time-zones/Australia/Lord_Howe'],
            [42, 'AU', 'Australia', 'Australia/Melbourne', 'UTC +10:00', 'https://timezonedb.com/time-zones/Australia/Melbourne'],
            [43, 'AU', 'Australia', 'Australia/Perth', 'UTC +08:00', 'https://timezonedb.com/time-zones/Australia/Perth'],
            [44, 'AU', 'Australia', 'Australia/Sydney', 'UTC +10:00', 'https://timezonedb.com/time-zones/Australia/Sydney'],
            [45, 'AT', 'Austria', 'Europe/Vienna', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Vienna'],
            [46, 'AZ', 'Azerbaijan', 'Asia/Baku', 'UTC +04:00', 'https://timezonedb.com/time-zones/Asia/Baku'],
            [47, 'BS', 'Bahamas', 'America/Nassau', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Nassau'],
            [48, 'BH', 'Bahrain', 'Asia/Bahrain', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Bahrain'],
            [49, 'BD', 'Bangladesh', 'Asia/Dhaka', 'UTC +06:00', 'https://timezonedb.com/time-zones/Asia/Dhaka'],
            [50, 'BB', 'Barbados', 'America/Barbados', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Barbados'],
            [51, 'BY', 'Belarus', 'Europe/Minsk', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Minsk'],
            [52, 'BE', 'Belgium', 'Europe/Brussels', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Brussels'],
            [53, 'BZ', 'Belize', 'America/Belize', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Belize'],
            [54, 'BJ', 'Benin', 'Africa/Porto-Novo', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Porto-Novo'],
            [55, 'BM', 'Bermuda', 'Atlantic/Bermuda', 'UTC -03:00', 'https://timezonedb.com/time-zones/Atlantic/Bermuda'],
            [56, 'BT', 'Bhutan', 'Asia/Thimphu', 'UTC +06:00', 'https://timezonedb.com/time-zones/Asia/Thimphu'],
            [57, 'BO', 'Bolivia, Plurinational State of', 'America/La_Paz', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/La_Paz'],
            [58, 'BQ', 'Bonaire, Sint Eustatius and Saba', 'America/Kralendijk', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Kralendijk'],
            [59, 'BA', 'Bosnia and Herzegovina', 'Europe/Sarajevo', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Sarajevo'],
            [60, 'BW', 'Botswana', 'Africa/Gaborone', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Gaborone'],
            [61, 'BR', 'Brazil', 'America/Araguaina', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Araguaina'],
            [62, 'BR', 'Brazil', 'America/Bahia', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Bahia'],
            [63, 'BR', 'Brazil', 'America/Belem', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Belem'],
            [64, 'BR', 'Brazil', 'America/Boa_Vista', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Boa_Vista'],
            [65, 'BR', 'Brazil', 'America/Campo_Grande', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Campo_Grande'],
            [66, 'BR', 'Brazil', 'America/Cuiaba', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Cuiaba'],
            [67, 'BR', 'Brazil', 'America/Eirunepe', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Eirunepe'],
            [68, 'BR', 'Brazil', 'America/Fortaleza', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Fortaleza'],
            [69, 'BR', 'Brazil', 'America/Maceio', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Maceio'],
            [70, 'BR', 'Brazil', 'America/Manaus', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Manaus'],
            [71, 'BR', 'Brazil', 'America/Noronha', 'UTC -02:00', 'https://timezonedb.com/time-zones/America/Noronha'],
            [72, 'BR', 'Brazil', 'America/Porto_Velho', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Porto_Velho'],
            [73, 'BR', 'Brazil', 'America/Recife', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Recife'],
            [74, 'BR', 'Brazil', 'America/Rio_Branco', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Rio_Branco'],
            [75, 'BR', 'Brazil', 'America/Santarem', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Santarem'],
            [76, 'BR', 'Brazil', 'America/Sao_Paulo', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Sao_Paulo'],
            [77, 'IO', 'British Indian Ocean Territory', 'Indian/Chagos', 'UTC +06:00', 'https://timezonedb.com/time-zones/Indian/Chagos'],
            [78, 'BN', 'Brunei Darussalam', 'Asia/Brunei', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Brunei'],
            [79, 'BG', 'Bulgaria', 'Europe/Sofia', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Sofia'],
            [80, 'BF', 'Burkina Faso', 'Africa/Ouagadougou', 'UTC', 'https://timezonedb.com/time-zones/Africa/Ouagadougou'],
            [81, 'BI', 'Burundi', 'Africa/Bujumbura', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Bujumbura'],
            [82, 'KH', 'Cambodia', 'Asia/Phnom_Penh', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Phnom_Penh'],
            [83, 'CM', 'Cameroon', 'Africa/Douala', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Douala'],
            [84, 'CA', 'Canada', 'America/Atikokan', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Atikokan'],
            [85, 'CA', 'Canada', 'America/Blanc-Sablon', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Blanc-Sablon'],
            [86, 'CA', 'Canada', 'America/Cambridge_Bay', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Cambridge_Bay'],
            [87, 'CA', 'Canada', 'America/Creston', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Creston'],
            [88, 'CA', 'Canada', 'America/Dawson', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Dawson'],
            [89, 'CA', 'Canada', 'America/Dawson_Creek', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Dawson_Creek'],
            [90, 'CA', 'Canada', 'America/Edmonton', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Edmonton'],
            [91, 'CA', 'Canada', 'America/Fort_Nelson', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Fort_Nelson'],
            [92, 'CA', 'Canada', 'America/Glace_Bay', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Glace_Bay'],
            [93, 'CA', 'Canada', 'America/Goose_Bay', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Goose_Bay'],
            [94, 'CA', 'Canada', 'America/Halifax', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Halifax'],
            [95, 'CA', 'Canada', 'America/Inuvik', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Inuvik'],
            [96, 'CA', 'Canada', 'America/Iqaluit', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Iqaluit'],
            [97, 'CA', 'Canada', 'America/Moncton', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Moncton'],
            [98, 'CA', 'Canada', 'America/Rankin_Inlet', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Rankin_Inlet'],
            [99, 'CA', 'Canada', 'America/Regina', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Regina'],
            [100, 'CA', 'Canada', 'America/Resolute', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Resolute'],
            [101, 'CA', 'Canada', 'America/St_Johns', 'UTC -02:30', 'https://timezonedb.com/time-zones/America/St_Johns'],
            [102, 'CA', 'Canada', 'America/Swift_Current', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Swift_Current'],
            [103, 'CA', 'Canada', 'America/Toronto', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Toronto'],
            [104, 'CA', 'Canada', 'America/Vancouver', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Vancouver'],
            [105, 'CA', 'Canada', 'America/Whitehorse', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Whitehorse'],
            [106, 'CA', 'Canada', 'America/Winnipeg', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Winnipeg'],
            [107, 'CV', 'Cape Verde', 'Atlantic/Cape_Verde', 'UTC -01:00', 'https://timezonedb.com/time-zones/Atlantic/Cape_Verde'],
            [108, 'KY', 'Cayman Islands', 'America/Cayman', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Cayman'],
            [109, 'CF', 'Central African Republic', 'Africa/Bangui', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Bangui'],
            [110, 'TD', 'Chad', 'Africa/Ndjamena', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Ndjamena'],
            [111, 'CL', 'Chile', 'America/Punta_Arenas', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Punta_Arenas'],
            [112, 'CL', 'Chile', 'America/Santiago', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Santiago'],
            [113, 'CL', 'Chile', 'Pacific/Easter', 'UTC -05:00', 'https://timezonedb.com/time-zones/Pacific/Easter'],
            [114, 'CN', 'China', 'Asia/Shanghai', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Shanghai'],
            [115, 'CN', 'China', 'Asia/Urumqi', 'UTC +06:00', 'https://timezonedb.com/time-zones/Asia/Urumqi'],
            [116, 'CX', 'Christmas Island', 'Indian/Christmas', 'UTC +07:00', 'https://timezonedb.com/time-zones/Indian/Christmas'],
            [117, 'CC', 'Cocos (Keeling) Islands', 'Indian/Cocos', 'UTC +06:30', 'https://timezonedb.com/time-zones/Indian/Cocos'],
            [118, 'CO', 'Colombia', 'America/Bogota', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Bogota'],
            [119, 'KM', 'Comoros', 'Indian/Comoro', 'UTC +03:00', 'https://timezonedb.com/time-zones/Indian/Comoro'],
            [120, 'CG', 'Congo', 'Africa/Brazzaville', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Brazzaville'],
            [121, 'CD', 'Congo, the Democratic Republic of the', 'Africa/Kinshasa', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Kinshasa'],
            [122, 'CD', 'Congo, the Democratic Republic of the', 'Africa/Lubumbashi', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Lubumbashi'],
            [123, 'CK', 'Cook Islands', 'Pacific/Rarotonga', 'UTC -10:00', 'https://timezonedb.com/time-zones/Pacific/Rarotonga'],
            [124, 'CR', 'Costa Rica', 'America/Costa_Rica', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Costa_Rica'],
            [125, 'HR', 'Croatia', 'Europe/Zagreb', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Zagreb'],
            [126, 'CU', 'Cuba', 'America/Havana', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Havana'],
            [127, 'CW', 'Curaçao', 'America/Curacao', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Curacao'],
            [128, 'CY', 'Cyprus', 'Asia/Famagusta', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Famagusta'],
            [129, 'CY', 'Cyprus', 'Asia/Nicosia', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Nicosia'],
            [130, 'CZ', 'Czech Republic', 'Europe/Prague', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Prague'],
            [131, 'CI', 'Côte d\'Ivoire', 'Africa/Abidjan', 'UTC', 'https://timezonedb.com/time-zones/Africa/Abidjan'],
            [132, 'DK', 'Denmark', 'Europe/Copenhagen', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Copenhagen'],
            [133, 'DJ', 'Djibouti', 'Africa/Djibouti', 'UTC +03:00', 'https://timezonedb.com/time-zones/Africa/Djibouti'],
            [134, 'DM', 'Dominica', 'America/Dominica', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Dominica'],
            [135, 'DO', 'Dominican Republic', 'America/Santo_Domingo', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Santo_Domingo'],
            [136, 'EC', 'Ecuador', 'America/Guayaquil', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Guayaquil'],
            [137, 'EC', 'Ecuador', 'Pacific/Galapagos', 'UTC -06:00', 'https://timezonedb.com/time-zones/Pacific/Galapagos'],
            [138, 'EG', 'Egypt', 'Africa/Cairo', 'UTC +03:00', 'https://timezonedb.com/time-zones/Africa/Cairo'],
            [139, 'SV', 'El Salvador', 'America/El_Salvador', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/El_Salvador'],
            [140, 'GQ', 'Equatorial Guinea', 'Africa/Malabo', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Malabo'],
            [141, 'ER', 'Eritrea', 'Africa/Asmara', 'UTC +03:00', 'https://timezonedb.com/time-zones/Africa/Asmara'],
            [142, 'EE', 'Estonia', 'Europe/Tallinn', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Tallinn'],
            [143, 'ET', 'Ethiopia', 'Africa/Addis_Ababa', 'UTC +03:00', 'https://timezonedb.com/time-zones/Africa/Addis_Ababa'],
            [144, 'FK', 'Falkland Islands (Malvinas)', 'Atlantic/Stanley', 'UTC -03:00', 'https://timezonedb.com/time-zones/Atlantic/Stanley'],
            [145, 'FO', 'Faroe Islands', 'Atlantic/Faroe', 'UTC +01:00', 'https://timezonedb.com/time-zones/Atlantic/Faroe'],
            [146, 'FJ', 'Fiji', 'Pacific/Fiji', 'UTC +12:00', 'https://timezonedb.com/time-zones/Pacific/Fiji'],
            [147, 'FI', 'Finland', 'Europe/Helsinki', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Helsinki'],
            [148, 'FR', 'France', 'Europe/Paris', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Paris'],
            [149, 'GF', 'French Guiana', 'America/Cayenne', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Cayenne'],
            [150, 'PF', 'French Polynesia', 'Pacific/Gambier', 'UTC -09:00', 'https://timezonedb.com/time-zones/Pacific/Gambier'],
            [151, 'PF', 'French Polynesia', 'Pacific/Marquesas', 'UTC -09:30', 'https://timezonedb.com/time-zones/Pacific/Marquesas'],
            [152, 'PF', 'French Polynesia', 'Pacific/Tahiti', 'UTC -10:00', 'https://timezonedb.com/time-zones/Pacific/Tahiti'],
            [153, 'TF', 'French Southern Territories', 'Indian/Kerguelen', 'UTC +05:00', 'https://timezonedb.com/time-zones/Indian/Kerguelen'],
            [154, 'GA', 'Gabon', 'Africa/Libreville', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Libreville'],
            [155, 'GM', 'Gambia', 'Africa/Banjul', 'UTC', 'https://timezonedb.com/time-zones/Africa/Banjul'],
            [156, 'GE', 'Georgia', 'Asia/Tbilisi', 'UTC +04:00', 'https://timezonedb.com/time-zones/Asia/Tbilisi'],
            [157, 'DE', 'Germany', 'Europe/Berlin', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Berlin'],
            [158, 'DE', 'Germany', 'Europe/Busingen', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Busingen'],
            [159, 'GH', 'Ghana', 'Africa/Accra', 'UTC', 'https://timezonedb.com/time-zones/Africa/Accra'],
            [160, 'GI', 'Gibraltar', 'Europe/Gibraltar', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Gibraltar'],
            [161, 'GR', 'Greece', 'Europe/Athens', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Athens'],
            [162, 'GL', 'Greenland', 'America/Danmarkshavn', 'UTC', 'https://timezonedb.com/time-zones/America/Danmarkshavn'],
            [163, 'GL', 'Greenland', 'America/Nuuk', 'UTC -02:00', 'https://timezonedb.com/time-zones/America/Nuuk'],
            [164, 'GL', 'Greenland', 'America/Scoresbysund', 'UTC', 'https://timezonedb.com/time-zones/America/Scoresbysund'],
            [165, 'GL', 'Greenland', 'America/Thule', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Thule'],
            [166, 'GD', 'Grenada', 'America/Grenada', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Grenada'],
            [167, 'GP', 'Guadeloupe', 'America/Guadeloupe', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Guadeloupe'],
            [168, 'GU', 'Guam', 'Pacific/Guam', 'UTC +10:00', 'https://timezonedb.com/time-zones/Pacific/Guam'],
            [169, 'GT', 'Guatemala', 'America/Guatemala', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Guatemala'],
            [170, 'GG', 'Guernsey', 'Europe/Guernsey', 'UTC +01:00', 'https://timezonedb.com/time-zones/Europe/Guernsey'],
            [171, 'GN', 'Guinea', 'Africa/Conakry', 'UTC', 'https://timezonedb.com/time-zones/Africa/Conakry'],
            [172, 'GW', 'Guinea-Bissau', 'Africa/Bissau', 'UTC', 'https://timezonedb.com/time-zones/Africa/Bissau'],
            [173, 'GY', 'Guyana', 'America/Guyana', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Guyana'],
            [174, 'HT', 'Haiti', 'America/Port-au-Prince', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Port-au-Prince'],
            [175, 'VA', 'Holy See (Vatican City State)', 'Europe/Vatican', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Vatican'],
            [176, 'HN', 'Honduras', 'America/Tegucigalpa', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Tegucigalpa'],
            [177, 'HK', 'Hong Kong', 'Asia/Hong_Kong', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Hong_Kong'],
            [178, 'HU', 'Hungary', 'Europe/Budapest', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Budapest'],
            [179, 'IS', 'Iceland', 'Atlantic/Reykjavik', 'UTC', 'https://timezonedb.com/time-zones/Atlantic/Reykjavik'],
            [180, 'IN', 'India', 'Asia/Kolkata', 'UTC +05:30', 'https://timezonedb.com/time-zones/Asia/Kolkata'],
            [181, 'ID', 'Indonesia', 'Asia/Jakarta', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Jakarta'],
            [182, 'ID', 'Indonesia', 'Asia/Jayapura', 'UTC +09:00', 'https://timezonedb.com/time-zones/Asia/Jayapura'],
            [183, 'ID', 'Indonesia', 'Asia/Makassar', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Makassar'],
            [184, 'ID', 'Indonesia', 'Asia/Pontianak', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Pontianak'],
            [185, 'IR', 'Iran, Islamic Republic of', 'Asia/Tehran', 'UTC +03:30', 'https://timezonedb.com/time-zones/Asia/Tehran'],
            [186, 'IQ', 'Iraq', 'Asia/Baghdad', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Baghdad'],
            [187, 'IE', 'Ireland', 'Europe/Dublin', 'UTC +01:00', 'https://timezonedb.com/time-zones/Europe/Dublin'],
            [188, 'IM', 'Isle of Man', 'Europe/Isle_of_Man', 'UTC +01:00', 'https://timezonedb.com/time-zones/Europe/Isle_of_Man'],
            [189, 'IL', 'Israel', 'Asia/Jerusalem', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Jerusalem'],
            [190, 'IT', 'Italy', 'Europe/Rome', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Rome'],
            [191, 'JM', 'Jamaica', 'America/Jamaica', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Jamaica'],
            [192, 'JP', 'Japan', 'Asia/Tokyo', 'UTC +09:00', 'https://timezonedb.com/time-zones/Asia/Tokyo'],
            [193, 'JE', 'Jersey', 'Europe/Jersey', 'UTC +01:00', 'https://timezonedb.com/time-zones/Europe/Jersey'],
            [194, 'JO', 'Jordan', 'Asia/Amman', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Amman'],
            [195, 'KZ', 'Kazakhstan', 'Asia/Almaty', 'UTC +06:00', 'https://timezonedb.com/time-zones/Asia/Almaty'],
            [196, 'KZ', 'Kazakhstan', 'Asia/Aqtau', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Aqtau'],
            [197, 'KZ', 'Kazakhstan', 'Asia/Aqtobe', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Aqtobe'],
            [198, 'KZ', 'Kazakhstan', 'Asia/Atyrau', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Atyrau'],
            [199, 'KZ', 'Kazakhstan', 'Asia/Oral', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Oral'],
            [200, 'KZ', 'Kazakhstan', 'Asia/Qostanay', 'UTC +06:00', 'https://timezonedb.com/time-zones/Asia/Qostanay'],
            [201, 'KZ', 'Kazakhstan', 'Asia/Qyzylorda', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Qyzylorda'],
            [202, 'KE', 'Kenya', 'Africa/Nairobi', 'UTC +03:00', 'https://timezonedb.com/time-zones/Africa/Nairobi'],
            [203, 'KI', 'Kiribati', 'Pacific/Kanton', 'UTC +13:00', 'https://timezonedb.com/time-zones/Pacific/Kanton'],
            [204, 'KI', 'Kiribati', 'Pacific/Kiritimati', 'UTC +14:00', 'https://timezonedb.com/time-zones/Pacific/Kiritimati'],
            [205, 'KI', 'Kiribati', 'Pacific/Tarawa', 'UTC +12:00', 'https://timezonedb.com/time-zones/Pacific/Tarawa'],
            [206, 'KP', 'Korea, Democratic People\'s Republic of', 'Asia/Pyongyang', 'UTC +09:00', 'https://timezonedb.com/time-zones/Asia/Pyongyang'],
            [207, 'KR', 'Korea, Republic of', 'Asia/Seoul', 'UTC +09:00', 'https://timezonedb.com/time-zones/Asia/Seoul'],
            [208, 'KW', 'Kuwait', 'Asia/Kuwait', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Kuwait'],
            [209, 'KG', 'Kyrgyzstan', 'Asia/Bishkek', 'UTC +06:00', 'https://timezonedb.com/time-zones/Asia/Bishkek'],
            [210, 'LA', 'Lao People\'s Democratic Republic', 'Asia/Vientiane', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Vientiane'],
            [211, 'LV', 'Latvia', 'Europe/Riga', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Riga'],
            [212, 'LB', 'Lebanon', 'Asia/Beirut', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Beirut'],
            [213, 'LS', 'Lesotho', 'Africa/Maseru', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Maseru'],
            [214, 'LR', 'Liberia', 'Africa/Monrovia', 'UTC', 'https://timezonedb.com/time-zones/Africa/Monrovia'],
            [215, 'LY', 'Libya', 'Africa/Tripoli', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Tripoli'],
            [216, 'LI', 'Liechtenstein', 'Europe/Vaduz', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Vaduz'],
            [217, 'LT', 'Lithuania', 'Europe/Vilnius', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Vilnius'],
            [218, 'LU', 'Luxembourg', 'Europe/Luxembourg', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Luxembourg'],
            [219, 'MO', 'Macao', 'Asia/Macau', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Macau'],
            [220, 'MK', 'Macedonia, the Former Yugoslav Republic of', 'Europe/Skopje', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Skopje'],
            [221, 'MG', 'Madagascar', 'Indian/Antananarivo', 'UTC +03:00', 'https://timezonedb.com/time-zones/Indian/Antananarivo'],
            [222, 'MW', 'Malawi', 'Africa/Blantyre', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Blantyre'],
            [223, 'MY', 'Malaysia', 'Asia/Kuala_Lumpur', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Kuala_Lumpur'],
            [224, 'MY', 'Malaysia', 'Asia/Kuching', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Kuching'],
            [225, 'MV', 'Maldives', 'Indian/Maldives', 'UTC +05:00', 'https://timezonedb.com/time-zones/Indian/Maldives'],
            [226, 'ML', 'Mali', 'Africa/Bamako', 'UTC', 'https://timezonedb.com/time-zones/Africa/Bamako'],
            [227, 'MT', 'Malta', 'Europe/Malta', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Malta'],
            [228, 'MH', 'Marshall Islands', 'Pacific/Kwajalein', 'UTC +12:00', 'https://timezonedb.com/time-zones/Pacific/Kwajalein'],
            [229, 'MH', 'Marshall Islands', 'Pacific/Majuro', 'UTC +12:00', 'https://timezonedb.com/time-zones/Pacific/Majuro'],
            [230, 'MQ', 'Martinique', 'America/Martinique', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Martinique'],
            [231, 'MR', 'Mauritania', 'Africa/Nouakchott', 'UTC', 'https://timezonedb.com/time-zones/Africa/Nouakchott'],
            [232, 'MU', 'Mauritius', 'Indian/Mauritius', 'UTC +04:00', 'https://timezonedb.com/time-zones/Indian/Mauritius'],
            [233, 'YT', 'Mayotte', 'Indian/Mayotte', 'UTC +03:00', 'https://timezonedb.com/time-zones/Indian/Mayotte'],
            [234, 'MX', 'Mexico', 'America/Bahia_Banderas', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Bahia_Banderas'],
            [235, 'MX', 'Mexico', 'America/Cancun', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Cancun'],
            [236, 'MX', 'Mexico', 'America/Chihuahua', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Chihuahua'],
            [237, 'MX', 'Mexico', 'America/Ciudad_Juarez', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Ciudad_Juarez'],
            [238, 'MX', 'Mexico', 'America/Hermosillo', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Hermosillo'],
            [239, 'MX', 'Mexico', 'America/Matamoros', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Matamoros'],
            [240, 'MX', 'Mexico', 'America/Mazatlan', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Mazatlan'],
            [241, 'MX', 'Mexico', 'America/Merida', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Merida'],
            [242, 'MX', 'Mexico', 'America/Mexico_City', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Mexico_City'],
            [243, 'MX', 'Mexico', 'America/Monterrey', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Monterrey'],
            [244, 'MX', 'Mexico', 'America/Ojinaga', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Ojinaga'],
            [245, 'MX', 'Mexico', 'America/Tijuana', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Tijuana'],
            [246, 'FM', 'Micronesia, Federated States of', 'Pacific/Chuuk', 'UTC +10:00', 'https://timezonedb.com/time-zones/Pacific/Chuuk'],
            [247, 'FM', 'Micronesia, Federated States of', 'Pacific/Kosrae', 'UTC +11:00', 'https://timezonedb.com/time-zones/Pacific/Kosrae'],
            [248, 'FM', 'Micronesia, Federated States of', 'Pacific/Pohnpei', 'UTC +11:00', 'https://timezonedb.com/time-zones/Pacific/Pohnpei'],
            [249, 'MD', 'Moldova, Republic of', 'Europe/Chisinau', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Chisinau'],
            [250, 'MC', 'Monaco', 'Europe/Monaco', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Monaco'],
            [251, 'MN', 'Mongolia', 'Asia/Choibalsan', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Choibalsan'],
            [252, 'MN', 'Mongolia', 'Asia/Hovd', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Hovd'],
            [253, 'MN', 'Mongolia', 'Asia/Ulaanbaatar', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Ulaanbaatar'],
            [254, 'ME', 'Montenegro', 'Europe/Podgorica', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Podgorica'],
            [255, 'MS', 'Montserrat', 'America/Montserrat', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Montserrat'],
            [256, 'MA', 'Morocco', 'Africa/Casablanca', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Casablanca'],
            [257, 'MA', 'Morocco', 'Africa/El_Aaiun', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/El_Aaiun'],
            [258, 'MZ', 'Mozambique', 'Africa/Maputo', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Maputo'],
            [259, 'MM', 'Myanmar', 'Asia/Yangon', 'UTC +06:30', 'https://timezonedb.com/time-zones/Asia/Yangon'],
            [260, 'NA', 'Namibia', 'Africa/Windhoek', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Windhoek'],
            [261, 'NR', 'Nauru', 'Pacific/Nauru', 'UTC +12:00', 'https://timezonedb.com/time-zones/Pacific/Nauru'],
            [262, 'NP', 'Nepal', 'Asia/Kathmandu', 'UTC +05:45', 'https://timezonedb.com/time-zones/Asia/Kathmandu'],
            [263, 'NL', 'Netherlands', 'Europe/Amsterdam', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Amsterdam'],
            [264, 'NC', 'New Caledonia', 'Pacific/Noumea', 'UTC +11:00', 'https://timezonedb.com/time-zones/Pacific/Noumea'],
            [265, 'NZ', 'New Zealand', 'Pacific/Auckland', 'UTC +13:00', 'https://timezonedb.com/time-zones/Pacific/Auckland'],
            [266, 'NZ', 'New Zealand', 'Pacific/Chatham', 'UTC +13:45', 'https://timezonedb.com/time-zones/Pacific/Chatham'],
            [267, 'NI', 'Nicaragua', 'America/Managua', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Managua'],
            [268, 'NE', 'Niger', 'Africa/Niamey', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Niamey'],
            [269, 'NG', 'Nigeria', 'Africa/Lagos', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Lagos'],
            [270, 'NU', 'Niue', 'Pacific/Niue', 'UTC -11:00', 'https://timezonedb.com/time-zones/Pacific/Niue'],
            [271, 'NF', 'Norfolk Island', 'Pacific/Norfolk', 'UTC +11:00', 'https://timezonedb.com/time-zones/Pacific/Norfolk'],
            [272, 'MP', 'Northern Mariana Islands', 'Pacific/Saipan', 'UTC +10:00', 'https://timezonedb.com/time-zones/Pacific/Saipan'],
            [273, 'NO', 'Norway', 'Europe/Oslo', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Oslo'],
            [274, 'OM', 'Oman', 'Asia/Muscat', 'UTC +04:00', 'https://timezonedb.com/time-zones/Asia/Muscat'],
            [275, 'PK', 'Pakistan', 'Asia/Karachi', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Karachi'],
            [276, 'PW', 'Palau', 'Pacific/Palau', 'UTC +09:00', 'https://timezonedb.com/time-zones/Pacific/Palau'],
            [277, 'PS', 'Palestine, State of', 'Asia/Gaza', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Gaza'],
            [278, 'PS', 'Palestine, State of', 'Asia/Hebron', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Hebron'],
            [279, 'PA', 'Panama', 'America/Panama', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Panama'],
            [280, 'PG', 'Papua New Guinea', 'Pacific/Bougainville', 'UTC +11:00', 'https://timezonedb.com/time-zones/Pacific/Bougainville'],
            [281, 'PG', 'Papua New Guinea', 'Pacific/Port_Moresby', 'UTC +10:00', 'https://timezonedb.com/time-zones/Pacific/Port_Moresby'],
            [282, 'PY', 'Paraguay', 'America/Asuncion', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Asuncion'],
            [283, 'PE', 'Peru', 'America/Lima', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Lima'],
            [284, 'PH', 'Philippines', 'Asia/Manila', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Manila'],
            [285, 'PN', 'Pitcairn', 'Pacific/Pitcairn', 'UTC -08:00', 'https://timezonedb.com/time-zones/Pacific/Pitcairn'],
            [286, 'PL', 'Poland', 'Europe/Warsaw', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Warsaw'],
            [287, 'PT', 'Portugal', 'Atlantic/Azores', 'UTC', 'https://timezonedb.com/time-zones/Atlantic/Azores'],
            [288, 'PT', 'Portugal', 'Atlantic/Madeira', 'UTC +01:00', 'https://timezonedb.com/time-zones/Atlantic/Madeira'],
            [289, 'PT', 'Portugal', 'Europe/Lisbon', 'UTC +01:00', 'https://timezonedb.com/time-zones/Europe/Lisbon'],
            [290, 'PR', 'Puerto Rico', 'America/Puerto_Rico', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Puerto_Rico'],
            [291, 'QA', 'Qatar', 'Asia/Qatar', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Qatar'],
            [292, 'RO', 'Romania', 'Europe/Bucharest', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Bucharest'],
            [293, 'RU', 'Russian Federation', 'Asia/Anadyr', 'UTC +12:00', 'https://timezonedb.com/time-zones/Asia/Anadyr'],
            [294, 'RU', 'Russian Federation', 'Asia/Barnaul', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Barnaul'],
            [295, 'RU', 'Russian Federation', 'Asia/Chita', 'UTC +09:00', 'https://timezonedb.com/time-zones/Asia/Chita'],
            [296, 'RU', 'Russian Federation', 'Asia/Irkutsk', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Irkutsk'],
            [297, 'RU', 'Russian Federation', 'Asia/Kamchatka', 'UTC +12:00', 'https://timezonedb.com/time-zones/Asia/Kamchatka'],
            [298, 'RU', 'Russian Federation', 'Asia/Khandyga', 'UTC +09:00', 'https://timezonedb.com/time-zones/Asia/Khandyga'],
            [299, 'RU', 'Russian Federation', 'Asia/Krasnoyarsk', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Krasnoyarsk'],
            [300, 'RU', 'Russian Federation', 'Asia/Magadan', 'UTC +11:00', 'https://timezonedb.com/time-zones/Asia/Magadan'],
            [301, 'RU', 'Russian Federation', 'Asia/Novokuznetsk', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Novokuznetsk'],
            [302, 'RU', 'Russian Federation', 'Asia/Novosibirsk', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Novosibirsk'],
            [303, 'RU', 'Russian Federation', 'Asia/Omsk', 'UTC +06:00', 'https://timezonedb.com/time-zones/Asia/Omsk'],
            [304, 'RU', 'Russian Federation', 'Asia/Sakhalin', 'UTC +11:00', 'https://timezonedb.com/time-zones/Asia/Sakhalin'],
            [305, 'RU', 'Russian Federation', 'Asia/Srednekolymsk', 'UTC +11:00', 'https://timezonedb.com/time-zones/Asia/Srednekolymsk'],
            [306, 'RU', 'Russian Federation', 'Asia/Tomsk', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Tomsk'],
            [307, 'RU', 'Russian Federation', 'Asia/Ust-Nera', 'UTC +10:00', 'https://timezonedb.com/time-zones/Asia/Ust-Nera'],
            [308, 'RU', 'Russian Federation', 'Asia/Vladivostok', 'UTC +10:00', 'https://timezonedb.com/time-zones/Asia/Vladivostok'],
            [309, 'RU', 'Russian Federation', 'Asia/Yakutsk', 'UTC +09:00', 'https://timezonedb.com/time-zones/Asia/Yakutsk'],
            [310, 'RU', 'Russian Federation', 'Asia/Yekaterinburg', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Yekaterinburg'],
            [311, 'RU', 'Russian Federation', 'Europe/Astrakhan', 'UTC +04:00', 'https://timezonedb.com/time-zones/Europe/Astrakhan'],
            [312, 'RU', 'Russian Federation', 'Europe/Kaliningrad', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Kaliningrad'],
            [313, 'RU', 'Russian Federation', 'Europe/Kirov', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Kirov'],
            [314, 'RU', 'Russian Federation', 'Europe/Moscow', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Moscow'],
            [315, 'RU', 'Russian Federation', 'Europe/Samara', 'UTC +04:00', 'https://timezonedb.com/time-zones/Europe/Samara'],
            [316, 'RU', 'Russian Federation', 'Europe/Saratov', 'UTC +04:00', 'https://timezonedb.com/time-zones/Europe/Saratov'],
            [317, 'RU', 'Russian Federation', 'Europe/Ulyanovsk', 'UTC +04:00', 'https://timezonedb.com/time-zones/Europe/Ulyanovsk'],
            [318, 'RU', 'Russian Federation', 'Europe/Volgograd', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Volgograd'],
            [319, 'RW', 'Rwanda', 'Africa/Kigali', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Kigali'],
            [320, 'RE', 'Réunion', 'Indian/Reunion', 'UTC +04:00', 'https://timezonedb.com/time-zones/Indian/Reunion'],
            [321, 'BL', 'Saint Barthélemy', 'America/St_Barthelemy', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/St_Barthelemy'],
            [322, 'SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Atlantic/St_Helena', 'UTC', 'https://timezonedb.com/time-zones/Atlantic/St_Helena'],
            [323, 'KN', 'Saint Kitts and Nevis', 'America/St_Kitts', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/St_Kitts'],
            [324, 'LC', 'Saint Lucia', 'America/St_Lucia', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/St_Lucia'],
            [325, 'MF', 'Saint Martin (French part)', 'America/Marigot', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Marigot'],
            [326, 'PM', 'Saint Pierre and Miquelon', 'America/Miquelon', 'UTC -02:00', 'https://timezonedb.com/time-zones/America/Miquelon'],
            [327, 'VC', 'Saint Vincent and the Grenadines', 'America/St_Vincent', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/St_Vincent'],
            [328, 'WS', 'Samoa', 'Pacific/Apia', 'UTC +13:00', 'https://timezonedb.com/time-zones/Pacific/Apia'],
            [329, 'SM', 'San Marino', 'Europe/San_Marino', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/San_Marino'],
            [330, 'ST', 'Sao Tome and Principe', 'Africa/Sao_Tome', 'UTC', 'https://timezonedb.com/time-zones/Africa/Sao_Tome'],
            [331, 'SA', 'Saudi Arabia', 'Asia/Riyadh', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Riyadh'],
            [332, 'SN', 'Senegal', 'Africa/Dakar', 'UTC', 'https://timezonedb.com/time-zones/Africa/Dakar'],
            [333, 'RS', 'Serbia', 'Europe/Belgrade', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Belgrade'],
            [334, 'SC', 'Seychelles', 'Indian/Mahe', 'UTC +04:00', 'https://timezonedb.com/time-zones/Indian/Mahe'],
            [335, 'SL', 'Sierra Leone', 'Africa/Freetown', 'UTC', 'https://timezonedb.com/time-zones/Africa/Freetown'],
            [336, 'SG', 'Singapore', 'Asia/Singapore', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Singapore'],
            [337, 'SX', 'Sint Maarten (Dutch part)', 'America/Lower_Princes', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Lower_Princes'],
            [338, 'SK', 'Slovakia', 'Europe/Bratislava', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Bratislava'],
            [339, 'SI', 'Slovenia', 'Europe/Ljubljana', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Ljubljana'],
            [340, 'SB', 'Solomon Islands', 'Pacific/Guadalcanal', 'UTC +11:00', 'https://timezonedb.com/time-zones/Pacific/Guadalcanal'],
            [341, 'SO', 'Somalia', 'Africa/Mogadishu', 'UTC +03:00', 'https://timezonedb.com/time-zones/Africa/Mogadishu'],
            [342, 'ZA', 'South Africa', 'Africa/Johannesburg', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Johannesburg'],
            [343, 'GS', 'South Georgia and the South Sandwich Islands', 'Atlantic/South_Georgia', 'UTC -02:00', 'https://timezonedb.com/time-zones/Atlantic/South_Georgia'],
            [344, 'SS', 'South Sudan', 'Africa/Juba', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Juba'],
            [345, 'ES', 'Spain', 'Africa/Ceuta', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Ceuta'],
            [346, 'ES', 'Spain', 'Atlantic/Canary', 'UTC +01:00', 'https://timezonedb.com/time-zones/Atlantic/Canary'],
            [347, 'ES', 'Spain', 'Europe/Madrid', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Madrid'],
            [348, 'LK', 'Sri Lanka', 'Asia/Colombo', 'UTC +05:30', 'https://timezonedb.com/time-zones/Asia/Colombo'],
            [349, 'SD', 'Sudan', 'Africa/Khartoum', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Khartoum'],
            [350, 'SR', 'Suriname', 'America/Paramaribo', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Paramaribo'],
            [351, 'SJ', 'Svalbard and Jan Mayen', 'Arctic/Longyearbyen', 'UTC +02:00', 'https://timezonedb.com/time-zones/Arctic/Longyearbyen'],
            [352, 'SZ', 'Swaziland', 'Africa/Mbabane', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Mbabane'],
            [353, 'SE', 'Sweden', 'Europe/Stockholm', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Stockholm'],
            [354, 'CH', 'Switzerland', 'Europe/Zurich', 'UTC +02:00', 'https://timezonedb.com/time-zones/Europe/Zurich'],
            [355, 'SY', 'Syrian Arab Republic', 'Asia/Damascus', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Damascus'],
            [356, 'TW', 'Taiwan, Province of China', 'Asia/Taipei', 'UTC +08:00', 'https://timezonedb.com/time-zones/Asia/Taipei'],
            [357, 'TJ', 'Tajikistan', 'Asia/Dushanbe', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Dushanbe'],
            [358, 'TZ', 'Tanzania, United Republic of', 'Africa/Dar_es_Salaam', 'UTC +03:00', 'https://timezonedb.com/time-zones/Africa/Dar_es_Salaam'],
            [359, 'TH', 'Thailand', 'Asia/Bangkok', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Bangkok'],
            [360, 'TL', 'Timor-Leste', 'Asia/Dili', 'UTC +09:00', 'https://timezonedb.com/time-zones/Asia/Dili'],
            [361, 'TG', 'Togo', 'Africa/Lome', 'UTC', 'https://timezonedb.com/time-zones/Africa/Lome'],
            [362, 'TK', 'Tokelau', 'Pacific/Fakaofo', 'UTC +13:00', 'https://timezonedb.com/time-zones/Pacific/Fakaofo'],
            [363, 'TO', 'Tonga', 'Pacific/Tongatapu', 'UTC +13:00', 'https://timezonedb.com/time-zones/Pacific/Tongatapu'],
            [364, 'TT', 'Trinidad and Tobago', 'America/Port_of_Spain', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Port_of_Spain'],
            [365, 'TN', 'Tunisia', 'Africa/Tunis', 'UTC +01:00', 'https://timezonedb.com/time-zones/Africa/Tunis'],
            [366, 'TR', 'Turkey', 'Europe/Istanbul', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Istanbul'],
            [367, 'TM', 'Turkmenistan', 'Asia/Ashgabat', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Ashgabat'],
            [368, 'TC', 'Turks and Caicos Islands', 'America/Grand_Turk', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Grand_Turk'],
            [369, 'TV', 'Tuvalu', 'Pacific/Funafuti', 'UTC +12:00', 'https://timezonedb.com/time-zones/Pacific/Funafuti'],
            [370, 'UG', 'Uganda', 'Africa/Kampala', 'UTC +03:00', 'https://timezonedb.com/time-zones/Africa/Kampala'],
            [371, 'UA', 'Ukraine', 'Europe/Kyiv', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Kyiv'],
            [372, 'UA', 'Ukraine', 'Europe/Simferopol', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Simferopol'],
            [373, 'AE', 'United Arab Emirates', 'Asia/Dubai', 'UTC +04:00', 'https://timezonedb.com/time-zones/Asia/Dubai'],
            [374, 'GB', 'United Kingdom', 'Europe/London', 'UTC +01:00', 'https://timezonedb.com/time-zones/Europe/London'],
            [375, 'US', 'United States', 'America/Adak', 'UTC -09:00', 'https://timezonedb.com/time-zones/America/Adak'],
            [376, 'US', 'United States', 'America/Anchorage', 'UTC -08:00', 'https://timezonedb.com/time-zones/America/Anchorage'],
            [377, 'US', 'United States', 'America/Boise', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Boise'],
            [378, 'US', 'United States', 'America/Chicago', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Chicago'],
            [379, 'US', 'United States', 'America/Denver', 'UTC -06:00', 'https://timezonedb.com/time-zones/America/Denver'],
            [380, 'US', 'United States', 'America/Detroit', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Detroit'],
            [381, 'US', 'United States', 'America/Indiana/Indianapolis', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Indiana/Indianapolis'],
            [382, 'US', 'United States', 'America/Indiana/Knox', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Indiana/Knox'],
            [383, 'US', 'United States', 'America/Indiana/Marengo', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Indiana/Marengo'],
            [384, 'US', 'United States', 'America/Indiana/Petersburg', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Indiana/Petersburg'],
            [385, 'US', 'United States', 'America/Indiana/Tell_City', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Indiana/Tell_City'],
            [386, 'US', 'United States', 'America/Indiana/Vevay', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Indiana/Vevay'],
            [387, 'US', 'United States', 'America/Indiana/Vincennes', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Indiana/Vincennes'],
            [388, 'US', 'United States', 'America/Indiana/Winamac', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Indiana/Winamac'],
            [389, 'US', 'United States', 'America/Juneau', 'UTC -08:00', 'https://timezonedb.com/time-zones/America/Juneau'],
            [390, 'US', 'United States', 'America/Kentucky/Louisville', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Kentucky/Louisville'],
            [391, 'US', 'United States', 'America/Kentucky/Monticello', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Kentucky/Monticello'],
            [392, 'US', 'United States', 'America/Los_Angeles', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Los_Angeles'],
            [393, 'US', 'United States', 'America/Menominee', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/Menominee'],
            [394, 'US', 'United States', 'America/Metlakatla', 'UTC -08:00', 'https://timezonedb.com/time-zones/America/Metlakatla'],
            [395, 'US', 'United States', 'America/New_York', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/New_York'],
            [396, 'US', 'United States', 'America/Nome', 'UTC -08:00', 'https://timezonedb.com/time-zones/America/Nome'],
            [397, 'US', 'United States', 'America/North_Dakota/Beulah', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/North_Dakota/Beulah'],
            [398, 'US', 'United States', 'America/North_Dakota/Center', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/North_Dakota/Center'],
            [399, 'US', 'United States', 'America/North_Dakota/New_Salem', 'UTC -05:00', 'https://timezonedb.com/time-zones/America/North_Dakota/New_Salem'],
            [400, 'US', 'United States', 'America/Phoenix', 'UTC -07:00', 'https://timezonedb.com/time-zones/America/Phoenix'],
            [401, 'US', 'United States', 'America/Sitka', 'UTC -08:00', 'https://timezonedb.com/time-zones/America/Sitka'],
            [402, 'US', 'United States', 'America/Yakutat', 'UTC -08:00', 'https://timezonedb.com/time-zones/America/Yakutat'],
            [403, 'US', 'United States', 'Pacific/Honolulu', 'UTC -10:00', 'https://timezonedb.com/time-zones/Pacific/Honolulu'],
            [404, 'UM', 'United States Minor Outlying Islands', 'Pacific/Midway', 'UTC -11:00', 'https://timezonedb.com/time-zones/Pacific/Midway'],
            [405, 'UM', 'United States Minor Outlying Islands', 'Pacific/Wake', 'UTC +12:00', 'https://timezonedb.com/time-zones/Pacific/Wake'],
            [406, 'UY', 'Uruguay', 'America/Montevideo', 'UTC -03:00', 'https://timezonedb.com/time-zones/America/Montevideo'],
            [407, 'UZ', 'Uzbekistan', 'Asia/Samarkand', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Samarkand'],
            [408, 'UZ', 'Uzbekistan', 'Asia/Tashkent', 'UTC +05:00', 'https://timezonedb.com/time-zones/Asia/Tashkent'],
            [409, 'VU', 'Vanuatu', 'Pacific/Efate', 'UTC +11:00', 'https://timezonedb.com/time-zones/Pacific/Efate'],
            [410, 'VE', 'Venezuela, Bolivarian Republic of', 'America/Caracas', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Caracas'],
            [411, 'VN', 'Viet Nam', 'Asia/Ho_Chi_Minh', 'UTC +07:00', 'https://timezonedb.com/time-zones/Asia/Ho_Chi_Minh'],
            [412, 'VG', 'Virgin Islands, British', 'America/Tortola', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/Tortola'],
            [413, 'VI', 'Virgin Islands, U.S.', 'America/St_Thomas', 'UTC -04:00', 'https://timezonedb.com/time-zones/America/St_Thomas'],
            [414, 'WF', 'Wallis and Futuna', 'Pacific/Wallis', 'UTC +12:00', 'https://timezonedb.com/time-zones/Pacific/Wallis'],
            [415, 'YE', 'Yemen', 'Asia/Aden', 'UTC +03:00', 'https://timezonedb.com/time-zones/Asia/Aden'],
            [416, 'ZM', 'Zambia', 'Africa/Lusaka', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Lusaka'],
            [417, 'ZW', 'Zimbabwe', 'Africa/Harare', 'UTC +02:00', 'https://timezonedb.com/time-zones/Africa/Harare'],
            [418, 'AX', 'Åland Islands', 'Europe/Mariehamn', 'UTC +03:00', 'https://timezonedb.com/time-zones/Europe/Mariehamn'],
        ];

        // Insert timezones with explicit IDs
        foreach ($timezones as $timezone) {
            DB::table('timezones')->insert([
                'id' => $timezone[0],
                'country_code' => $timezone[1],
                'country_name' => $timezone[2],
                'time_zone' => $timezone[3],
                'gmt_offset' => $timezone[4],
                'timezone_link' => $timezone[5],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('Seeded ' . count($timezones) . ' timezones.');
    }
}
